server:
  port: 9001

#spring:
#  datasource:
#    url: ${DB_URL:jdbc:postgresql://localhost:5432/auth_db}
#    username: ${DB_USER:postgres}
#    password: ${DB_PASS:password}
#    driver-class-name: org.postgresql.Driver

resilience4j:
  circuitbreaker:
    instances:
      default:
        registerHealthIndicator: true
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 10000