version: '3.8'

services:
  # ====== Databases (оставлены без изменений) ======
  postgres-auth:
    image: postgres:15
    container_name: postgres-auth
    environment:
      POSTGRES_DB: auth_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password

  redis-auth:
    image: redis:7.4.0
    container_name: redis-auth
    restart: always
    environment:
      - REDIS_DATABASES=0
      - REDIS_PASSWORD=qwerty12345678

  postgres-user:
    image: postgres:15
    container_name: postgres-user
    environment:
      POSTGRES_DB: user_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password

  postgres-product:
    image: postgres:15
    container_name: postgres-product
    environment:
      POSTGRES_DB: product_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password

  postgres-cart:
    image: postgres:15
    container_name: postgres-cart
    environment:
      POSTGRES_DB: cart_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password

  postgres-order:
    image: postgres:15
    container_name: postgres-order
    environment:
      POSTGRES_DB: order_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password

  postgres-payment:
    image: postgres:15
    container_name: postgres-payment
    environment:
      POSTGRES_DB: payment_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password

  postgres-wms:
    image: postgres:15
    container_name: postgres-wms
    environment:
      POSTGRES_DB: wms_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password

  postgres-tracking:
    image: postgres:15
    container_name: postgres-tracking
    environment:
      POSTGRES_DB: tracking_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password

  postgres-notification:
    image: postgres:15
    container_name: postgres-notification
    environment:
      POSTGRES_DB: notification_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password

  postgres-review:
    image: postgres:15
    container_name: postgres-review
    environment:
      POSTGRES_DB: review_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password

  postgres-admin:
    image: postgres:15
    container_name: postgres-admin
    environment:
      POSTGRES_DB: admin_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password

  # ====== Message Broker ======
  kafka:
    image: bitnami/kafka:3.7
    container_name: kafka
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_CFG_LISTENERS: PLAINTEXT://:9092
      KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_CFG_ZOOKEEPER_CONNECT: zookeeper:2181
      ALLOW_PLAINTEXT_LISTENER: "yes"

  zookeeper:
    image: bitnami/zookeeper:3.8
    container_name: zookeeper
    environment:
      ALLOW_ANONYMOUS_LOGIN: "yes"

  # ====== Elasticsearch for Search Service ======
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.13.2
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9200/_cat/health"]
      interval: 30s
      timeout: 10s
      retries: 5

  # ====== Config, Discovery, Gateway ======
  config-server:
    build:
      context: ./config-server
    container_name: config-server
    environment:
      SPRING_PROFILES_ACTIVE: docker

  discovery-server:
    build:
      context: ./discovery-server
    container_name: discovery-server
    environment:
      SPRING_PROFILES_ACTIVE: docker

  api-gateway:
    build:
      context: ./api-gateway
    container_name: api-gateway
    environment:
      SPRING_PROFILES_ACTIVE: docker

  # ====== Microservices ======
  auth-service:
    build:
      context: ./auth-service
    container_name: auth-service
    environment:
      SPRING_PROFILES_ACTIVE: docker
      DB_URL: jdbc:postgresql://postgres-auth:5432/auth_db
      DB_USER: postgres
      DB_PASS: password
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092

  user-service:
    build:
      context: ./user-service
    container_name: user-service
    environment:
      SPRING_PROFILES_ACTIVE: docker
      DB_URL: jdbc:postgresql://postgres-user:5432/user_db
      DB_USER: postgres
      DB_PASS: password
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092

  product-service:
    build:
      context: ./product-service
    container_name: product-service
    environment:
      SPRING_PROFILES_ACTIVE: docker
      DB_URL: jdbc:postgresql://postgres-product:5432/product_db
      DB_USER: postgres
      DB_PASS: password
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092

  cart-service:
    build:
      context: ./cart-service
    container_name: cart-service
    environment:
      SPRING_PROFILES_ACTIVE: docker
      DB_URL: jdbc:postgresql://postgres-cart:5432/cart_db
      DB_USER: postgres
      DB_PASS: password
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092

  order-service:
    build:
      context: ./order-service
    container_name: order-service
    environment:
      SPRING_PROFILES_ACTIVE: docker
      DB_URL: jdbc:postgresql://postgres-order:5432/order_db
      DB_USER: postgres
      DB_PASS: password
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092

  payment-service:
    build:
      context: ./payment-service
    container_name: payment-service
    environment:
      SPRING_PROFILES_ACTIVE: docker
      DB_URL: jdbc:postgresql://postgres-payment:5432/payment_db
      DB_USER: postgres
      DB_PASS: password
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092

  wms-service:
    build:
      context: ./wms-service
    container_name: wms-service
    environment:
      SPRING_PROFILES_ACTIVE: docker
      DB_URL: jdbc:postgresql://postgres-wms:5432/wms_db
      DB_USER: postgres
      DB_PASS: password
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092

  tracking-service:
    build:
      context: ./tracking-service
    container_name: tracking-service
    environment:
      SPRING_PROFILES_ACTIVE: docker
      DB_URL: jdbc:postgresql://postgres-tracking:5432/tracking_db
      DB_USER: postgres
      DB_PASS: password
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092

  notification-service:
    build:
      context: ./notification-service
    container_name: notification-service
    environment:
      SPRING_PROFILES_ACTIVE: docker
      DB_URL: jdbc:postgresql://postgres-notification:5432/notification_db
      DB_USER: postgres
      DB_PASS: password
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092

  review-service:
    build:
      context: ./review-service
    container_name: review-service
    environment:
      SPRING_PROFILES_ACTIVE: docker
      DB_URL: jdbc:postgresql://postgres-review:5432/review_db
      DB_USER: postgres
      DB_PASS: password
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092

  admin-service:
    build:
      context: ./admin-service
    container_name: admin-service
    environment:
      SPRING_PROFILES_ACTIVE: docker
      DB_URL: jdbc:postgresql://postgres-admin:5432/admin_db
      DB_USER: postgres
      DB_PASS: password
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092

  search-service:
    build:
      context: ./search-service
    container_name: search-service
    environment:
      SPRING_PROFILES_ACTIVE: docker
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      PRODUCT_SERVICE_URL: http://product-service:9003
      SPRING_ELASTICSEARCH_URIS: http://elasticsearch:9200