version: '3.8'

services:
  # ====== Databases (оставлены без изменений) ======
  postgres-auth:
    networks:
      - internal

  redis-auth:
    networks:
      - internal

  postgres-user:
    networks:
      - internal

  postgres-product:
    networks:
      - internal

  postgres-cart:
    networks:
      - internal

  postgres-order:
    networks:
      - internal

  postgres-payment:
    networks:
      - internal

  postgres-wms:
    networks:
      - internal

  postgres-tracking:
    networks:
      - internal

  postgres-notification:
    networks:
      - internal

  postgres-review:
    networks:
      - internal

  postgres-admin:
    networks:
      - internal

  # ====== Message Broker ======
  kafka:
    depends_on:
      - zookeeper
    networks:
      - internal

  zookeeper:
    networks:
      - internal

  # ====== Elasticsearch for Search Service ======
  elasticsearch:
    networks:
      - internal

  # ====== Config, Discovery, Gateway ======
  config-server:
    networks:
      - internal

  discovery-server:
    networks:
      - internal

  api-gateway:
    ports:
      - "80:8080"
    networks:
      - internal
      - external
    depends_on:
      - config-server
      - discovery-server

  # ====== Microservices ======
  auth-service:
    networks:
      - internal
    depends_on:
      - postgres-auth
      - redis-auth
      - kafka
      - config-server
      - discovery-server

  user-service:
    networks:
      - internal
    depends_on:
      - postgres-user
      - kafka
      - config-server
      - discovery-server

  product-service:
    networks:
      - internal
    depends_on:
      - postgres-product
      - kafka
      - config-server
      - discovery-server

  cart-service:
    networks:
      - internal
    depends_on:
      - postgres-cart
      - kafka
      - config-server
      - discovery-server

  order-service:
    networks:
      - internal
    depends_on:
      - postgres-order
      - kafka
      - config-server
      - discovery-server

  payment-service:
    networks:
      - internal
    depends_on:
      - postgres-payment
      - kafka
      - config-server
      - discovery-server

  wms-service:
    networks:
      - internal
    depends_on:
      - postgres-wms
      - kafka
      - config-server
      - discovery-server

  tracking-service:
    networks:
      - internal
    depends_on:
      - postgres-tracking
      - kafka
      - config-server
      - discovery-server

  notification-service:
    networks:
      - internal
    depends_on:
      - postgres-notification
      - kafka
      - config-server
      - discovery-server

  review-service:
    networks:
      - internal
    depends_on:
      - postgres-review
      - kafka
      - config-server
      - discovery-server

  admin-service:
    networks:
      - internal
    depends_on:
      - postgres-admin
      - kafka
      - config-server
      - discovery-server

  search-service:
    networks:
      - internal
    depends_on:
      - elasticsearch
      - product-service
      - kafka
      - config-server
      - discovery-server

networks:
  internal:
    driver: bridge
    internal: true
  external:
    driver: bridge