server:
  port: 8080

spring:
  cloud:
    gateway:
      mvc:
        routes:
          # Примеры маршрутов, дополнять по мере добавления сервисов
          - id: user-service
            uri: lb://user-service
            predicates:
              - Path=/api/users/**
          # и т.д.
  security:
    oauth2:
      resourceserver:
        opaquetoken:
          client-id: j-service-client
          client-secret: j-service-client
          introspection-uri: ${SSO_URL:http://localhost:9001}/oauth2/token-info