server:
  port: 9012
spring:
  application:
    name: search-service
  elasticsearch:
    uris: ${ELASTICSEARCH_URI:localhost:9200}
#    username: ${ELASTICSEARCH_USER:}
#    password: ${ELASTICSEARCH_PASS:}
    connection-timeout: 2s
    socket-timeout: 10s

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    consumer:
      group-id: search-service-group
      auto-offset-reset: earliest
      enable-auto-commit: false

  auth-types:
    auth-header-enabled: true
    client-credentials-enabled: true
    authorization-code-enabled: true

  security:
    oauth2:
      resourceserver:
        opaquetoken:
          client-id: j-service-client
          client-secret: j-service-client
          introspection-uri: ${SSO_URL:http://localhost:9001}/oauth2/token-info

product-service:
  url: http://localhost:9003

search:
  index:
    name: products
  batch:
    size: 100