server:
  port: 9003

spring:
  application:
    name: product-service
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:kafka:9092}
    consumer:
      group-id: search-service-group
      auto-offset-reset: earliest
      enable-auto-commit: false

  datasource:
    url: ${DB_URL:jdbc:postgresql://postgres-product:5432/product_db}
    username: ${DB_USER:postgres}
    password: ${DB_PASS:password}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update

  auth-types:
    auth-header-enabled: true
    client-credentials-enabled: true
    authorization-code-enabled: true

  security:
    oauth2:
      resourceserver:
        opaquetoken:
          client-id: j-service-client
          client-secret: j-service-client
          introspection-uri: ${SSO_URL:http://auth-service:9001}/oauth2/token-info

resilience4j:
  circuitbreaker:
    instances:
      default:
        registerHealthIndicator: true
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 10000