server:
  port: 9004 # Port for Cart Service

spring:
  application:
    name: cart-service
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5434/cart_db}
    username: ${DB_USER:postgres}
    password: ${DB_PASS:password}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml


